project_id = "job-tracker-local"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.migrations]
enabled = false

[studio]
enabled = false

[auth]
enabled = true
site_url = "http://localhost:5173"
enable_signup = true
enable_confirmations = false

[analytics]
enabled = false
